spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mariadb://127.0.0.1:23306/mybatis?characterEncoding=utf-8&useSSL=false
  application:
    name: HelloService